# Generated by Django 2.1.5 on 2019-02-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='client_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photography',
            name='image_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolioiamges',
            name='p_id',
            field=models.IntegerField(),
        ),
    ]
